### ISSUE TITLE
JAVA Exception when file path contains spaces

### ISSUE THREAD

**Issue by baptadn** [Funstaff/Tika#1]
Hi,
When path contains a space the JAR throws an exception:

```
Exception in thread "main" java.net.MalformedURLException: no protocol: /var/www/doc/sample
    at java.net.URL.<init>(URL.java:585)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:412)
    at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:111)
```

For fixing this, you have to use the php function `escapeshellarg()` in https://github.com/Funstaff/Tika/blob/master/src/Funstaff/Tika/Wrapper.php#L139

```
$command = sprintf('%s %s', $command, escapeshellarg($doc->getPath()));
```

**Comment by ganchclub** [comment]
In another project, but your tip with escapeshellarg() helped to remove this exception type,
Thanks a lot
